server:
  port: 8081
spring:
  application:
    name: "backend-ARUS"
  devtools:
    add-properties: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  profiles:
    include: null
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=arus"
    username: "postgres"
    password: "admin"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
